using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace JokerApi
{
    /// <summary>
    /// This defines some basic functions that every iteration of this library should have!!
    /// </summary>
    /// <autogeneratedoc />
    /// TODO Edit XML Comment Template for IJokerHelper
    /// TODO (smzb): Should define some of that old XML stuff for settings etc
    public interface IJokerHelper
    {
        /// <summary>Adds the specified Num1.</summary>
        /// <param name="Num1">The Num1.</param>
        /// <param name="Num2">The num2.</param>
        /// <returns></returns>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for Add
        int Add(int Num1, int Num2);
        /// <summary>Subs the specified Num1.</summary>
        /// <param name="Num1">The Num1.</param>
        /// <param name="Num2">The Num2.</param>
        /// <returns></returns>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for Sub
        int Sub(int Num1, int Num2);
        /// <summary>Muls the specified Num1.</summary>
        /// <param name="Num1">The Num1.</param>
        /// <param name="Num2">The Num2.</param>
        /// <returns></returns>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for Mul
        int Mul(int Num1, int Num2);
        /// <summary>Divs the specified Num1.</summary>
        /// <param name="Num1">The Num1.</param>
        /// <param name="Num2">The Num2.</param>
        /// <returns></returns>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for Div
        int Div(int Num1, int Num2);
    }
}
