using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace JokerApi
{
    /// <summary>
    /// 
    /// </summary>
    /// <seealso cref="IJokerHelper" />
    /// <autogeneratedoc />
    /// TODO Edit XML Comment Template for JokerHelper
    public class JokerHelper : IJokerHelper
    {
        /// <summary>Adds the specified Num1.</summary>
        /// <param name="Num1">The Num1.</param>
        /// <param name="Num2">The Num2.</param>
        /// <returns></returns>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for Add
        public int Add(int Num1, int Num2)
        {
            var result = Num1 + Num2;
            return result;
        }

        /// <summary>Divs the specified Num1.</summary>
        /// <param name="Num1">The Num1.</param>
        /// <param name="Num2">The Num2.</param>
        /// <returns></returns>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for Div
        public int Div(int Num1, int Num2)
        {
            var result = Num1 / Num2;
            return result;
        }

        /// <summary>Muls the specified Num1.</summary>
        /// <param name="Num1">The Num1.</param>
        /// <param name="Num2">The Num2.</param>
        /// <returns></returns>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for Mul
        public int Mul(int Num1, int Num2)
        {
            var result = Num1 * Num2;
            return result;
        }

        /// <summary>Subs the specified Num1.</summary>
        /// <param name="Num1">The Num1.</param>
        /// <param name="Num2">The Num2.</param>
        /// <returns></returns>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for Sub
        public int Sub(int Num1, int Num2)
        {
            var result = Num1 + Num2;
            return result;
        }
    }
}
