using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using HostsEditCmd;

namespace HostsEditGui
{
    /// <summary>
    /// The MainForm Class, here we will handle all GUI interactions
    /// </summary>
    /// <seealso cref="System.Windows.Forms.Form" />
    /// <autogeneratedoc />
    /// TODO Edit XML Comment Template for MainForm
    public partial class MainForm : Form
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MainForm"/> class.
        /// </summary>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for #ctor
        public MainForm()
        {
            InitializeComponent();
        }
    }
}
